platform :ios, '6.1'
pod 'AFNetworking', '~> 2.4.1'
pod 'FMDB', '~> 2.4'
pod 'EGOImageLoading', '~> 0.0.1'
pod 'UMengAnalytics-NO-IDFA', '~> 3.5.11'
pod 'AdsMoGo-iOS-Lib',:git=>'https://github.com/chensj1901/AdsMoGo-iOS-Lib.git'
pod 'SJSettingRecode',:git=>'https://github.com/chensj1901/SJSettingRecode.git'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'RTLabel', '~> 1.0.1'
pod 'iRate', '~> 1.11.4'